kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-pacman-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  retention:
    hourly: 4
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - pacman
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: profile-gcs-pcerda-demolab
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: profile-gcs-pcerda-demolab
          namespace: kasten-io
        exportData:
          enabled: true
      retention: {}