---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pacman-role
  namespace: pacman
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - pacman
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pacman-rolebinding
  namespace: pacman
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pacman-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
- kind: ServiceAccount
  name: default
  namespace: pacman
