apiVersion: v1
data:
  initinsert.psql: |
    INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam VBR Socket','Socket',0.0,2000);
    INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam VBR VUL','VUL (10 pack)',10000.0,1500);
    INSERT INTO stock(product,unit,amount,price) VALUES ('Kasten K10','Node',10000.0,1500);
    INSERT INTO stock(product,unit,amount,price) VALUES ('Veeam Backup for M365','User',10000.0,1500.0);
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: stock-demo-configmap
  namespace: "stock-demo"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-demo-deploy
  namespace: "stock-demo"
  labels:
    app: stock-demo
    purpose: production
    dataprotection: k10-gold
    immutable: enabled  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-demo
  template:
    metadata:
      labels:
        app: stock-demo
    spec:
      containers:
        - name: stock-demo
          image: tdewin/stock-demo
          ports:
            - name: stock-demo
              containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: stock
            - name: POSTGRES_SERVER
              value: stockdb-postgresql
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PORT
              value: "5432"
            - name: ADMINKEY
              value: unlock
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: stockdb-postgresql
          volumeMounts:
          - name: config
            mountPath: "/var/stockdb"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: stock-demo-configmap


