kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-stock-demo-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  retention:
    hourly: 1  
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - stock-demo
  actions:
    - action: backup
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: profile-gcs-pcerda-demolab
          namespace: kasten-io
        exportData:
          enabled: true
      retention:
        hourly: 2