---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: stockdb-postgresql
  namespace: "stock-demo"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.9.1
    app.kubernetes.io/instance: stockdb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "TW1HelBMd3JneQ=="
  password: "bm90c2VjdXJl"
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
