kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-sockshop-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - sockshop
  actions:
    - action: backup
      backupParameters:
        profile:
          name: profile-azblob-pcerdak10sa
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: profile-azblob-pcerdak10sa
          namespace: kasten-io
        exportData:
          enabled: true
      retention:
        hourly: 4
        daily: 0
        weekly: 0
        monthly: 0
        yearly: 0
  retention:
    hourly: 0
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0